### ISSUE TITLE
installation errors

### ISSUE THREAD

**Issue by aslangabriel99** [aponsero/Resistome_ReadBased_Snakemake#1]
Hi, I tried to running your test. The error said conda malfunction. I have attached the log file. Would you like to help me fix this?
[2024-05-13T171758.647746.snakemake.log](https://github.com/aponsero/Resistome_ReadBased_Snakemake/files/15294145/2024-05-13T171758.647746.snakemake.log)

**Comment by aponsero** [comment]
Hello,
Ah, we are still currently finalising this pipeline for an upcoming paper submission. So the pipeline is currently under construction, and some parts may not work yet. I'll add a warning on the readme, sorry about that!

But I can try to help if you want, the log you sent did not upload properly, could you try again?

Alise
